tissot: qcom-caf: audio: audio_extn: Fix unused parameter warning in… … utils.c
The unused parameter warning appears if we are not building with
at least one of the following cflags enabled:

* DEV_ARBI_ENABLED
* SOUND_TRIGGER_ENABLED
* AUDIO_LISTEN_ENABLED

  hardware/qcom/audio/hal/audio_extn/utils.c:2522:55: error: unused parameter 'snd_device'
[-Werror,-Wunused-parameter]
  void audio_extn_utils_release_snd_device(snd_device_t snd_device)
                                                      ^

Change-Id: I694c683c9bfde60343f0f6ea8d806bc5e24437e6
Signed-off-by: Jabiyeff <cebiyevanar@gmail.com>